#!/bin/bash

help() {
  echo "Usage:"
  echo "  zservice cd <service_name>"
}

core() {
  if [ "$1" = "" ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi
  
  local service_name=$1
  if [ -z "${service_name}" ]; then
    log::error "service name is required"
    exit 1
  fi

  local service_path=$(service::get_path $service_name)
  if [ ! -d "$service_path" ]; then
    log::error "[$(timestamp)][service][cd] service($service_name) not found"
    exit 1
  fi

  cd $service_path
  exec $SHELL
}

run() {
  core $@
}

run $@
