#!/bin/bash

help() {
  echo "Usage:"
  echo "  zservice config <service_name> [options...]"
  echo ""
  echo "Options:"
  echo "  --edit                Edit config file"
  echo "  -h, --help            Print help"
}

core() {
  if [ "$1" = "" ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi
  
  local service_name=$1
  local args=${@:2}
  local edit=false
  if [ -z "${service_name}" ]; then
    log::error "service name is required"
    exit 1
  fi

  if [ "${args}" = "--edit" ]; then
    edit=true
  fi

  if [ "${edit}" = "true" ]; then
    local config_path=$(service::get_config_path $service_name)
    vim $config_path
    exit 0
  fi

  service::run $service_name config $args
}

run() {
  core $@
}

run $@
