#!/bin/bash

help() {
  echo "Download Service Repo, alias of pull_repo"
  echo ""
  echo "Usage:"
  echo "  zservice download <service_name> [options...]"
}

core() {
  if [ "$1" = "" ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  local name=$1
  local args=${@:2}

  if [ -z "$name" ]; then
    log::error "name is required"
    exit 1
  fi

  service::clone $name $args

  log::info "Successfully to download service (${name})"
}

run() {
  core $@
}

run $@
