#!/bin/bash

help() {
  echo "Usage:"
  echo "  zservice go <service_name>"
}

core() {
  if [ "$1" = "" ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi
  
  zservice cd $@
}

run() {
  core $@
}

run $@
