#!/bin/bash

help() {
  echo "Usage:"
  echo "  service go <service_name>"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  # @TODO
  local service=$1
  local module=$2

  if [ "$service" = "" ]; then
    cd $ZMICRO_PLUGINS_PATH/$PLUGIN_SERVICE_NAME
    exec $SHELL
    return 0
  fi

  if [ "$module" = "config" ]; then
    local service_config_path=$PLUGIN_SERVICE_CONFIGS/$service
    cd $service_config_path
    exec $SHELL
    exit 0
  elif [ "$module" = "data" ]; then
    local service_data_path=$PLUGIN_SERVICE_DATA/$service
    cd $service_data_path
    exec $SHELL
    exit 0
  fi

  zservice cd $@
}

run() {
  core $@
}

run $@
