#!/bin/bash

help() {
  echo "Usage:"
  echo "  zservice go <service_name>"
}

core() {
  if [ "$1" = "" ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  # @TODO
  local service=$1
  local module=$2
  if [ "$module" = "config" ]; then
    local service_config_path=$PLUGIN_SERVICE_CONFIGS/$service
    cd $service_config_path
    exec $SHELL
    exit 0
  fi
  
  zservice cd $@
}

run() {
  core $@
}

run $@
