#!/bin/bash

help() {
  echo "Usage:"
  echo "  zservice inspect <service_name> [options...]"
}

core() {
  if [ "$1" = "" ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi
  
  local service_name=$1
  local args=${@:2}
  if [ -z "${service_name}" ]; then
    log::error "service name is required"
    exit 1
  fi

  service::run $service_name config $args
}

run() {
  core $@
}

run $@
