#!/bin/bash

help() {
  echo "Usage:"
  echo "  zservice install <service>"
  echo ""
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi
  
  local name=$1
  if [ -z "$name" ]; then
    log::error "service name is requried"
    exit 1
  fi

  # @TODO
  local version=$2
  local alias_=$3
  if [ "$2" = "-v" ]; then
    version=$3
    alias_=$4
  fi

  service::install $name $version $alias_
}

run() {
  core $@
}

run $@
