#!/bin/bash

help() {
  echo "Usage:"
  echo "  zmicro service install <service>[@<version>] [alias]"
  echo ""
  echo "Args:"
  echo "  service - the service name, such as, redis, gzfly ..."
  echo "  version - the service version"
  echo "  alias   - the service new name, it is userful for multiple service instances"
  echo ""
  echo "Examples:"
  echo "  zmicro service install redis"
  echo "  zmicro service install redis@latest"
  echo "  zmicro service install redis@v1.0.0"
  echo "  zmicro service install redis https://private.example.com/namespace/redis"
  echo "  zmicro service install redis@v1.0.0 redis_service_name"
  echo "  zmicro service install redis --alias another_redis_name"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  # @1 install redis v1.2.3 redis_alias
  local name=$1
  local version=$2
  local alias_=$3

  if [ -z "$name" ]; then
    log::error "service name is requried"
    exit 1
  fi

  # @2 install redis -v v1.2.3 redis_alias
  if [ "$2" = "-v" ]; then
    version=$3
    alias_=$4
  elif [ "$2" = "--alias" ]; then
    # @4 install redis --alias another_redis_name
    if [ -z "$3" ]; then
      log::error "service alias is requried"
      exit 1
    fi
    
    alias_=$3
  fi

  # @3 install redis@v1.2.3 redis_alias
  if [ "$(version::at $name)" = "true" ]; then
    version=$(version::at_version $name)
    name=$(version::at_name $name)
    alias_=$2
  fi

  export SERVICE_AUTO_START=true
  service::install $name $version $alias_
}

run() {
  core $@
}

run $@
