#!/bin/bash

help() {
  echo "Usage:"
  echo "  zservice logs <service_name> [options...]"
}

core() {
  if [ "$1" = "" ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  local service_name=$1
  local args=${@:2}

  # @todo: add default args
  if [ -z "$args" ]; then
    args="-f --tail 100"
  fi

  service::run $service_name logs $args
}

run() {
  core $@
}

run $@
