#!/bin/bash

help() {
  echo "Usage:"
  echo "  zservice pull_repo <service_name> [options...]"
}

core() {
  if [ "$1" = "" ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  local name=$1
  local args=${@:2}

  if [ -z "$name" ]; then
    log::error "name is required"
    exit 1
  fi

  service::clone $name $args

  log::info "Successfully to pull service repo (${name})"
}

run() {
  core "$@"
}

run "$@"
