#!/bin/bash

help() {
  echo "Usage:"
  echo "  zservice pull_repo <service_name> [options...]"
}

core() {
  if [ "$1" = "" ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  local service_name=$1
  local args=${@:2}

  service::clone $service_name $args
}

run() {
  core $@
}

run $@
