#!/bin/bash

help() {
  echo "Usage:"
  echo "  zservice reload <service_name> [options...]"
}

core() {
  if [ "$1" = "" ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  # Exit when met error
  set -e

  local service_name=$1
  local args=${@:2}

  # stop
  service::run $service_name down $args
  # then start
  service::run $service_name up -d $args
}

run() {
  core $@
}

run $@
