#!/bin/bash

help() {
  echo "Usage:"
  echo "  zservice install <service>"
  echo ""
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi
  
  local name=$1
  if [ -z "$name" ]; then
    log::error "service name is requried"
    exit 1
  fi

  service::remove $name
}

run() {
  core $@
}

run $@
