#!/bin/bash

help() {
  echo "Usage:"
  echo "  zservice restart <service_name> [options...]"
  echo ""
  echo "Options:"
  echo "  -h, --help              Get help"
  echo "  -p, --pull              Upgrade the image"
  echo "  -u, --upgrade           Upgrade the image"
  echo ""
}

core() {
  if [ "$1" = "" ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  # Exit when met error
  set -e

  local service_name=
  local pull=false

  # set_pull_flag() {
  #   pull=true
  # }

  # local options=(
  #   "-h,--help              Get help            help"
  #   "-p,--pull              Upgrade the image   set_pull_flag"
  #   "-u,--upgrade           Upgrade the image   set_pull_flag"
  # )

  local args_length=${#@}
  local args_index=0
  while [ "$1" != "" ]; do
    args_index=$((args_index + 1))
    case $1 in
      -h | --help)
        help
        exit 0
        ;;
      -p | --pull)
        pull=true
        ;;
      -u | --upgrade)
        pull=true
        ;;
      *)
        if [ "$args_index" != "$args_length" ]; then
          log::error "Unknown option: $1"
          exit 1
        else
          service_name=$1
        fi
        ;;
    esac
    shift
  done

  # service::run $service_name restart $args

  # zmicro service stop $service_name
  # zmicro service start $service_name

  if [ "$pull" = "true" ]; then
    # 滚动更新
    # pull latest, make it as rolling update
    service::run $service_name pull
  fi

  # 检查是否需要 Build，有 image 目录
  service::build $service_name

  # stop
  service::run $service_name down --remove-orphans
  # then start
  service::run $service_name up -d
}

run() {
  core $@
}

run $@
