#!/bin/bash

help() {
  echo "Usage:"
  echo "  zservice stop <service_name> [options...]"
}

core() {
  if [ "$1" = "" ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  local service_name=$1
  local args=${@:2}
  service::run $service_name down $args
}

run() {
  core $@
}

run $@
