#!/bin/bash

help() {
  echo "Usage:"
  echo "  zservice switch <service_name> <version> [options...]"
  # echo ""
  # echo "    -h, --help              Get help"
  # echo "    -u, --update <version>  Set new version"
  echo ""
  echo "Example:"
  echo "  zservice switch ingress v1.0.0"
}

core() {
   if [ "$1" = "" ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  local name=$1
  local version=$2

  if [ -z "$name" ] || [ -z "$version" ]; then
    log::error "name and version are required"
    exit 1
  fi

  # 1. switch to the specified version
  service::switch $name $version

  # 2. restart the service
  zmicro service restart --pull $name
}

run() {
  core $@
}

run $@
