#!/bin/bash

help() {
  echo "Usage:"
  echo "  zservice update <service_name> [options...]"
  # echo ""
  # echo "    -h, --help              Get help"
  # echo "    -u, --update <version>  Set new version"
}

core() {
   if [ "$1" = "" ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  local service_name=$1
  local args=${@:2}

  service::update $name $args
}

run() {
  core $@
}

run $@
