#!/bin/bash

help() {
  echo "Usage:"
  echo "  zservice upgrade <service_name> <version> [options...]"
  # echo ""
  # echo "    -h, --help              Get help"
  # echo "    -u, --update <version>  Set new version"
  echo ""
  echo "Example:"
  echo "  zservice upgrade ingress v1.0.0"
}

core() {
   if [ "$1" = "" ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  local name=$1
  local version=$2

  if [ -z "$name" ] || [ -z "$version" ]; then
    log::error "name and version are required"
    exit 1
  fi

  # 1. [stop] stop the origin service
  #   why should we stop the origin service?
  #     - because service code (docker-compose.yml) may be changed
  #     - maybe services are not the names, so we need to stop all services first
  #     - it doesnot like update date service image only
  zmicro service stop $name

  # 1. [switch] switch the specified version
  zmicro service switch $name $version
}

run() {
  core $@
}

run $@
