#!/bin/bash

help() {
  echo "Usage:"
  echo "  zservice upgrade [options...] <service_name> <version>"
  # echo ""
  # echo "    -h, --help              Get help"
  # echo "    -u, --update <version>  Set new version"
  echo ""
  echo "Options:"
  echo "  --rolling    Rolling mode will not stop service before upgrade"
  echo ""
  echo "Example:"
  echo "  zservice upgrade ingress v1.0.0"
  echo ""
}

core() {
  if [ "$1" = "" ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  local name=""
  local version=""

  while [[ $# -gt 0 ]]; do
    local key=$1
    local value=$2
    case $key in
    -r | --rolling)
      os::set_var is_rolling_upgrade true
      shift
      ;;
    *)
      if [ "$(string::match $key ^-)" = "true" ]; then
        log::error "[$(timestamp)] ERROR: unknown parameter \"$key\""
        exit 1
      fi

      if [ -z "$name" ]; then
        name=$key
        shift
      elif [ -z "$version" ]; then
        version=$key
        shift
      else
        log::error "[$(timestamp)] unknown parameter \"$key\""
        exit 1
      fi
      ;;
    esac
  done

  if [ -z "$name" ]; then
    log::error "name are required"
    exit 1
  fi

  if [ -z "$version" ]; then
    version=latest
  fi

  if [ "$is_rolling_upgrade" != "true" ]; then
    # 1. [stop] stop the origin service
    #   why should we stop the origin service?
    #     - because service code (${PLUGIN_SERVICE_DOCKER_COMPOSE_FILE_NAME}) may be changed
    #     - maybe services are not the names, so we need to stop all services first
    #     - it doesnot like update date service image only
    zmicro service stop $name
  fi

  # 1. [switch] switch the specified version
  zmicro service switch $name $version
}

run() {
  core $@
}

run $@
