#!/bin/bash

help() {
  echo "Usage:"
  echo "  swarm version <service>"
  echo ""
  echo "    -h, --help              Get help"
  echo "    -u, --update <version>  Set new version"
}

core() {
  local name=$1
  if [ "$name" = "" ]; then
    log::error "service name is required"
    exit 1
  fi

  service::version_echo $name
}

run() {
  core $@
}

run $@
