#!/bin/bash

help() {
  echo "Show local service config"
  echo ""
  echo "Usage:"
  echo "  zservice local config"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  local context=$PWD
  local dockerfile_path=$context/Dockerfile
  local dotenv_path=$context/.env
  local zmicro_rc=$context/.zmicro
  if [ ! -f "$dockerfile_path" ]; then
    log::error "Dockerfile not found"
    exit 1
  fi

  if [ ! -f "$dotenv_path" ]; then
    log::error ".env not found"
    exit 1
  fi

  if [ ! -f "$zmicro_rc" ]; then
    log::error ".zmicro not found"
    exit 1
  fi

  config::load_file $zmicro_rc

  export PLUGIN_SERVICE_LOCAL_CONTEXT=$context
  export PLUGIN_SERVICE_LOCAL_ENV_FILE=$dotenv_path
  export PLUGIN_SERVICE_LOCAL_NAME=$SERVICE_LOCAL_NAME

  cd $ZMICRO_PLUGINS_PATH/service/config/local

  $PLUGIN_SERVICE_DOCKER_COMPOSE config
}

run() {
  core $@
}

run $@
